# Generated by Django 6.0 on 2026-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('semester', models.IntegerField()),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('APPLIED', 'Applied'), ('LAB', 'Lab'), ('PROJECT', 'Project'), ('SOFT', 'Soft Skill')], max_length=20)),
                ('weightage', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institute_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
