# Generated by Django 5.2.9 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_studentprofile_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_accuracy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_correct_answers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_highest_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_level_label',
            field=models.CharField(blank=True, choices=[('FOUNDATION', 'Foundation'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_total_questions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
