# Generated by Django 5.2.9 on 2026-02-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_studentprofile_assessment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProctoringEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assessment_session_id", models.CharField(db_index=True, max_length=64)),
                ("assessment_skill", models.CharField(blank=True, max_length=100)),
                ("event_type", models.CharField(choices=[("ASSESSMENT_STARTED", "Assessment Started"), ("ANSWER_SUBMITTED", "Answer Submitted"), ("TAB_SWITCH", "Tab Switch"), ("WINDOW_BLUR", "Window Blur"), ("COPY_BLOCKED", "Copy Blocked"), ("CUT_BLOCKED", "Cut Blocked"), ("PASTE_BLOCKED", "Paste Blocked"), ("CONTEXT_MENU_BLOCKED", "Context Menu Blocked"), ("SHORTCUT_BLOCKED", "Shortcut Blocked"), ("ASSESSMENT_COMPLETED", "Assessment Completed"), ("ASSESSMENT_TERMINATED", "Assessment Terminated")], max_length=40)),
                ("suspicious", models.BooleanField(default=False)),
                ("suspicious_reasons", models.JSONField(blank=True, default=list)),
                ("client_timestamp", models.DateTimeField(blank=True, null=True)),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="proctoring_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-server_timestamp"],
                "indexes": [
                    models.Index(fields=["user", "assessment_session_id", "server_timestamp"], name="academics_pr_user_id_bf8eca_idx"),
                    models.Index(fields=["suspicious", "server_timestamp"], name="academics_pr_suspici_9bc6d2_idx"),
                ],
            },
        ),
    ]
