# Generated by Django 4.2 on 2026-02-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_proctoringevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proctoringevent',
            new_name='academics_p_user_id_97cf3e_idx',
            old_name='academics_pr_user_id_bf8eca_idx',
        ),
        migrations.RenameIndex(
            model_name='proctoringevent',
            new_name='academics_p_suspici_cb5473_idx',
            old_name='academics_pr_suspici_9bc6d2_idx',
        ),
    ]
