# Generated by Django 4.2 on 2026-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_rename_academics_pr_user_id_bf8eca_idx_academics_p_user_id_97cf3e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_domain_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
